name: flutter_chip8_example
description: An example app for using the Flutter chip8 library

version: 1.0.0+1

environment:
  sdk: ">=2.3.0-dev.0.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_chip8:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/ibm_logo.ch8
    - assets/framed_mk1_samways_1980.ch8
    - assets/framed_mk2_samways_1980.ch8
    - assets/clock_bill_fisher_1981.ch8
    - assets/life_samways_1980.ch8
    - assets/keypad_test_hap_2006.ch8
    - assets/space_invaders_david_winter.ch8
    - assets/bc_test.ch8